### ISSUE TITLE
Gets stuck on keys that have accent options

### ISSUE THREAD

**Issue by rolandpatel** [freerunnering/SwipeSelection#10]
SwipeSelection is a wonderful tweak but when I try swiping it inevitably will get stuck on a key and pull up the accented variations. The swiping ability still works, but the pop-out of the key remains up and any subsequent keystroke usually results in that popped-out letter being  displayed. Really hinders the flow of typing.

This video shows exactly what problem I'm encountering: http://www.youtube.com/watch?v=EsJaspzzCqM

The description of the video says that the problem was supposed to be changed in a previous update? FYI I'm running on a 4S with 6.1.

**Comment by freerunnering** [comment]
I think I fixed this a year or 2 ago?
