### ISSUE TITLE
Renders Japanese keyboard almost unusable

### ISSUE THREAD

**Issue by psiclopz** [freerunnering/SwipeSelection#16]
When trying to use a Japanese keyboard with this installed it becomes almost unusable.  The reason being when typing Kana you touch one of the 12 keys and then slide up, down, left or right to select the kana you want.  With swipe selection install this makes your cursor fly away from the end every time you slide anywhere but right.  The only way to get around this is to hold the key down for 1-2 seconds until all 4 options appear, and then select one.

It'd be really great if we had a settings section that let you say, only enable shift selecting, or if it allowed you to set the keyboards it is enabled for.  I've now unfortunately had to uninstall this due to this issue :(

**Comment by freerunnering** [comment]
Same as #20 (which includes a screenshot so I'll close this one).
