### ISSUE TITLE
in Safari ios 8.3 its not working

### ISSUE THREAD

**Issue by tarsonis123** [freerunnering/SwipeSelection#60]
Hey there,

really one must have tweak on cydia for me. Unfortunetly I can't use it in Safari text input editor like this one I type in right now. Its not working. I have the bloard tweak installed if this is an issue?
Anyway I can fix this?

Works with my other apps though

**Comment by freerunnering** [comment]
Fixed, will be released later today

**Comment by freerunnering** [comment]
Update has been release

**Comment by tarsonis123** [comment]
Great! Thanks for the update
