### ISSUE TITLE
1.5.2-1 is broken on IOS 5.1.1

### ISSUE THREAD

**Issue by Ppeur** [freerunnering/SwipeSelection#64]
I updated it today and saw that it didn't work anymore...
It's not related to other tweaks because I downgraded and it was fine (1.5.1-1).

**Comment by freerunnering** [comment]
I think my computer can't compile for iOS 5 anymore, it's not a code change.
Sorry :(

**Comment by amandamana** [comment]
Same problem on iPad 1. Unfortunately, I've been unable to locate old version 1.5.1-1 anywhere. Bigboss just has the most recent and web searches have not helped. Does anyone have the old deb?

EDIT: [found it here](http://apt.thebigboss.org/repofiles/cydia/debs2.0/swipeselection_1.5.1-1.deb) by guessing the URL. It wasn't exposed in Cydia as a downgrade.
