### ISSUE TITLE
I can't delete SwipeSelection 

### ISSUE THREAD

**Issue by SaudK** [freerunnering/SwipeSelection#66]
It's weird I can't delete this tweak..  The weird is its gone from cydia still I can use it now!? Help me

**Comment by freerunnering** [comment]
iOS 9 added something like SwipeSelection to the iPhone 6S. If you have a 6S you can use something like SwipeSelection by force pushing into the keyboard.

**Comment by SaudK** [comment]
No I have iPhone 6

**Comment by SaudK** [comment]
Oh I was using tweak called peek-a-poo
Which is enables force touch to old version of the iPhone.  

That's why I can use force touching the keyboard 
Anyway thanks.
